// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ads.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAdvertisement = `-- name: CreateAdvertisement :one
INSERT INTO advertisements(id, title, description, image_address, price, created_at, updated_at, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) 
RETURNING id, title, description, image_address, price, created_at, updated_at, user_id
`

type CreateAdvertisementParams struct {
	Title        string
	Description  string
	ImageAddress string
	Price        int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
}

func (q *Queries) CreateAdvertisement(ctx context.Context, arg CreateAdvertisementParams) (Advertisement, error) {
	row := q.db.QueryRowContext(ctx, createAdvertisement,
		arg.Title,
		arg.Description,
		arg.ImageAddress,
		arg.Price,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Advertisement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImageAddress,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
